##################################################################################
# Cloudify Bash built in types and plugins definitions.
##################################################################################

plugins:
    bash:
        executor: host_agent
        source: https://github.com/cloudify-cosmo/cloudify-bash-plugin/archive/1.2.zip

node_types:

    # A web server configured with bash scripts
    cloudify.types.bash.web_server:
        derived_from: cloudify.types.web_server
        interfaces:
            cloudify.interfaces.lifecycle:
                - create: bash.bash_runner.tasks.run
                - configure: bash.bash_runner.tasks.run
                - start: bash.bash_runner.tasks.run
                - stop: bash.bash_runner.tasks.run
                - delete: bash.bash_runner.tasks.run
        properties:
            scripts: {}

    # An app server configured with bash scripts
    cloudify.types.bash.app_server:
        derived_from: cloudify.types.app_server
        interfaces:
            cloudify.interfaces.lifecycle:
                - create: bash.bash_runner.tasks.run
                - configure: bash.bash_runner.tasks.run
                - start: bash.bash_runner.tasks.run
                - stop: bash.bash_runner.tasks.run
                - delete: bash.bash_runner.tasks.run
        properties:
            scripts: {}

    # A db server configured with bash scripts
    cloudify.types.bash.db_server:
        derived_from: cloudify.types.db_server
        interfaces:
            cloudify.interfaces.lifecycle:
                - create: bash.bash_runner.tasks.run
                - configure: bash.bash_runner.tasks.run
                - start: bash.bash_runner.tasks.run
                - stop: bash.bash_runner.tasks.run
                - delete: bash.bash_runner.tasks.run
        properties:
            scripts: {}

    # A message bus server configured with bash scripts
    cloudify.types.bash.message_bus_server:
        derived_from: cloudify.types.message_bus_server
        interfaces:
            cloudify.interfaces.lifecycle:
                - create: bash.bash_runner.tasks.run
                - configure: bash.bash_runner.tasks.run
                - start: bash.bash_runner.tasks.run
                - stop: bash.bash_runner.tasks.run
                - delete: bash.bash_runner.tasks.run
        properties:
            scripts: {}

    # An app module configured with bash scripts
    cloudify.types.bash.app_module:
        derived_from: cloudify.types.app_module
        interfaces:
            cloudify.interfaces.lifecycle:
                - create: bash.bash_runner.tasks.run
                - configure: bash.bash_runner.tasks.run
                - start: bash.bash_runner.tasks.run
                - stop: bash.bash_runner.tasks.run
                - delete: bash.bash_runner.tasks.run
        properties:
            scripts: {}