#!/bin/sh
echo CLOUDIFY_NODE_ID=${CLOUDIFY_NODE_ID}
echo CLOUDIFY_BLUEPRINT_ID=${CLOUDIFY_BLUEPRINT_ID}
echo CLOUDIFY_DEPLOYMENT_ID=${CLOUDIFY_DEPLOYMENT_ID}
echo CLOUDIFY_MANAGER_IP=${CLOUDIFY_MANAGER_IP}
echo CLOUDIFY_EXECUTION_ID=${CLOUDIFY_EXECUTION_ID}
echo CLOUDIFY_FILE_SERVER_BLUEPRINT_ROOT=${CLOUDIFY_FILE_SERVER_BLUEPRINT_ROOT}
echo port=${port}
echo url=${url}
echo node_id=${node_id}

